apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pod
  name: test-pod
spec:
  containers:
  - image: sataga/usersupport-daily-report:latest
    name: test-pod
    resources: 
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: GITHUB_TOKEN
      valueFrom:
          secretKeyRef:
            key: github-token
            name: github-secret
    - name: GITHUB_MAIL
      valueFrom:
          secretKeyRef:
            key: github-mail
            name: github-secret
    args:
      - "daily-report"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
