apiVersion: batch/v1beta1
kind: Cronjob
metadata:
  name: usersupport-dairy-report
spec:
  schedule: "10 1 * * 1-5"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: usersupport-dairy-report
              image: sataga/go-kubernetes:latest
              imagePullPolicy: Always
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                      secretKeyRef:
                        key: GITHUB_TOKEN
                        name: usersupport-report
          restartPolicy: Never
